pipeline {
    agent any
    stages {
        stage('test AWS credentials') {
            steps {
                withAWS(credentials: 'new', region: 'ap-south-1') 
                {
                    sh 'python pipeline4/create_instance.py'
                }
            }
        }
    }
}
