pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                script {
                     withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
                                      credentialsId: 'BOB',
                                      accessKeyVariable: 'AKIAWIVDCUIS5PYYZ55Q',
                                      secretKeyVariable: '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']]) {
                    sh 'aws ec2 describe-instances --region ap-south-1'
                                          
                                      }
                }
            }
        }
    }
}
