pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                script {
                     withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
                                      credentialsId: 'BOB',
                                      accessKeyVariable: 'AKIATLZVEHTZOIOIGBXF'
',
                                      secretKeyVariable: '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
']]) {
                    sh 'aws ec2 describe-instances --region ap-south-1'
                                          
                                      }
                }
            }
        }
    }
}
