pipeline {
    agent any
    stages {
        stage('test AWS credentials') {
            steps {
                withAWS(credentials: 'admin', region: 'ap-south-1') 
                {
                    sh 'python pipeline5/policy.json'
                }
            }
        }
    }
}
